import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/cn";
import NavbarSimple from "@/components/ui/navbar-simple";

const robotoSlab = Roboto_Slab({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(robotoSlab.className, "antialiased")}>
        <header className="fixed inset-x-0 z-10">
          <NavbarSimple />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
